project_id = "uwfuuhhcjlxgyeecpeii"

[functions.redeem-activation-code]
verify_jwt = true

[functions.serve-raw-script]
verify_jwt = false

[functions.ai-chat]
verify_jwt = true

[functions.lua-code-assist]
verify_jwt = true

[functions.discord-bot-api]
verify_jwt = false

[functions.discord-interactions]
verify_jwt = false

[functions.downgrade-subscription]
verify_jwt = true